name: Build Windows 11 Home+Pro Bypass ISO

on:
  workflow_dispatch:

jobs:  
  patch-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone bypass tool
        run: git clone https://github.com/JosephM101/Force-Windows-11-Install.git

      - name: Install gdown
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install gdown

      - name: Download ISO from Google Drive using gdown
        shell: pwsh
        run: |
          python -m gdown --id 1EGTi6h_NsDogEH7OJp6J3vxBf411CADO --output Win11_24H2_English_x64.iso

      - name: Apply TPM/SecureBoot/CPU bypass
        shell: pwsh
        run: |
          cd Force-Windows-11-Install
          .\Win11-TPM-RegBypass.ps1 `
            -Source "$Env:GITHUB_WORKSPACE\Win11_24H2_English_x64.iso" `
            -Destination "$Env:GITHUB_WORKSPACE\Win11_24H2_English_x64.iso"

      - name: Upload patched ISO
        uses: actions/upload-artifact@v4
        with:
          name: win11-24h2-bypass-iso
          path: Win11_24H2_English_x64.iso
