name: Build Windows 11 Bypass ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable script execution
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Clone UUP dump miniserver (official)
        run: git clone https://github.com/uup-dump/miniserver

      - name: Download and prepare UUP files for Home + Pro
        shell: powershell
        run: |
          cd miniserver
          .\download.php `
            id=d3e090ef-98f1-43a7-8d5e-76f449c1ee02 `
            pack=en-us `
            edition=home,professional `
            arch=x64 `
            no-links=1

      - name: Build Windows 11 ISO
        shell: powershell
        run: |
          cd miniserver
          .\uup_download_windows.ps1

      - name: Clone TPM Bypass Tool
        run: git clone https://github.com/JosephM101/Force-Windows-11-Install.git

      - name: Apply TPM/SecureBoot Bypass Patch
        shell: powershell
        run: |
          cd Force-Windows-11-Install
          $iso = Get-ChildItem "$Env:GITHUB_WORKSPACE" -Filter *.iso | Select-Object -First 1
          .\Win11-TPM-RegBypass.ps1 `
            -Source $iso.FullName `
            -Destination "$Env:GITHUB_WORKSPACE\\windows-11-bypass.iso"

      - name: Upload Bypass ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win11-bypass-iso
          path: windows-11-bypass.iso
