name: Build Windows 11 Bypass ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable script execution
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Clone UUP Dump ISO builder
        run: git clone https://github.com/rgl/uup-dump-get-windows-iso.git

      - name: Generate Windows 11 ISO with Home and Pro editions
        shell: powershell
        run: |
          cd uup-dump-get-windows-iso
          .\uup-dump-get-windows-iso.ps1 d3e090ef-98f1-43a7-8d5e-76f449c1ee02

      - name: Clone bypass tool
        run: git clone https://github.com/JosephM101/Force-Windows-11-Install.git

      - name: Apply registry-bypass patch
        shell: powershell
        run: |
          cd Force-Windows-11-Install
          .\Win11-TPM-RegBypass.ps1 `
            -Source "../uup-dump-get-windows-iso/output/windows-11.iso" `
            -Destination "windows-11-bypass.iso"

      - name: Upload bypass ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: win11-bypass-iso
          path: Force-Windows-11-Install/windows-11-bypass.iso
