name: Build Windows 11 Home+Pro Bypass ISO

on:
  workflow_dispatch:

jobs:
  patch-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone bypass tool
        run: |
          git clone https://github.com/JosephM101/Force-Windows-11-Install.git

      - name: Download ISO from Google Drive
        shell: pwsh
        run: |
          $fileId   = "1EGTi6h_NsDogEH7OJp6J3vxBf411CADO"
          $fileName = "Win11_24H2_English_x64.iso"

          # Build the base Google Drive URL
          $baseUrl = "https://docs.google.com/uc?export=download&id=$fileId"
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession

          # First request to get the confirm token (for large files)
          $initial = Invoke-WebRequest -Uri $baseUrl -WebSession $session -UseBasicParsing
          if ($initial.Content -match 'confirm=([0-9A-Za-z_]+)') {
            $confirm    = $matches[1]
            $downloadUrl = "https://docs.google.com/uc?export=download&confirm=$confirm&id=$fileId"
          }
          else {
            # No token needed (small file or already cached)
            $downloadUrl = $baseUrl
          }

          # Download the ISO
          Write-Host "Downloading ISO to $fileName"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $fileName -WebSession $session -UseBasicParsing
          Write-Host "Download complete: $fileName"

      - name: Apply TPM/SecureBoot/CPU bypass
        shell: pwsh
        run: |
          cd Force-Windows-11-Install

          # Overwrite the original ISO with the bypassed version
          .\Win11-TPM-RegBypass.ps1 `
            -Source "$Env:GITHUB_WORKSPACE\Win11_24H2_English_x64.iso" `
            -Destination "$Env:GITHUB_WORKSPACE\Win11_24H2_English_x64.iso"

      - name: Upload patched ISO
        uses: actions/upload-artifact@v4
        with:
          name: win11-24h2-bypass-iso
          path: Win11_24H2_English_x64.iso
