name: Build Windows 11 Bypass ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Enable Script Execution
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Download ISO with Fido
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/pbatard/Fido/archive/refs/heads/master.zip -OutFile fido.zip
          Expand-Archive fido.zip -DestinationPath .
          cd Fido-master
          .\fido.ps1 -win 11 -Lang "English (United States)"
    
      - name: Clone Bypass Script
        run: git clone https://github.com/JosephM101/Force-Windows-11-Install.git

      - name: Patch ISO with Bypass
        shell: powershell
        run: |
          $iso = Get-ChildItem -Path "$Env:GITHUB_WORKSPACE\Fido-master" -Filter *.iso -Recurse | Select-Object -First 1
          cd Force-Windows-11-Install
          .\Win11-TPM-RegBypass.ps1 `
            -Source "$($iso.FullName)" `
            -Destination "$Env:GITHUB_WORKSPACE\Win11_Bypassed.iso"

      - name: Upload Patched ISO
        uses: actions/upload-artifact@v4
        with:
          name: Win11_Bypassed_ISO
          path: Win11_Bypassed.iso
