name: Build Windows 11 Bypass ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable script execution
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Generate stock Windows 11 ISO
        shell: powershell
        run: |
          .\uup-dump-get-windows-iso.ps1 windows-11-home-pro
          
      - name: Clone bypass tool
        run: git clone https://github.com/JosephM101/Force-Windows-11-Install.git

      - name: Apply registry-bypass patch
        shell: powershell
        run: |
          cd Force-Windows-11-Install
          $iso = Get-ChildItem ../uup-dump-get-windows-iso/output/ -Filter *.iso | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $iso) {
          throw "No ISO found in ../uup-dump-get-windows-iso/output/"
          }
          .\Win11-TPM-RegBypass.ps1 `
          -Source $iso.FullName `
          -Destination "windows-11-bypass.iso"
      
      - name: Upload bypass ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: win11-bypass-iso
          path: Force-Windows-11-Install/windows-11-bypass.iso
