name: Build Windows 11 Bypass ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable script execution
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Download UUP Dump ZIP for Windows 11 Home + Pro (24H2)
        run: |
          curl -L -o uup.zip "https://uup.rg-adguard.net/dl.php?id=d3e090ef-98f1-43a7-8d5e-76f449c1ee02&pack=en-us&edition=professional,home&arch=x64"
          tar -xf uup.zip || unzip uup.zip

      - name: Build Windows 11 ISO with Home + Pro
        shell: powershell
        run: |
          .\uup_download_windows.ps1

      - name: Clone TPM Bypass Tool
        run: git clone https://github.com/JosephM101/Force-Windows-11-Install.git

      - name: Apply TPM/SecureBoot Bypass Patch
        shell: powershell
        run: |
          cd Force-Windows-11-Install
          .\Win11-TPM-RegBypass.ps1 `
            -Source "$Env:GITHUB_WORKSPACE\\*.iso" `
            -Destination "$Env:GITHUB_WORKSPACE\\windows-11-bypass.iso"

      - name: Upload Bypass ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win11-bypass-iso
          path: windows-11-bypass.iso
